### ISSUE TITLE
Create products_in_storage API

### ISSUE THREAD

**Issue by pablotardio** [1-2020almacen/almacen-serve#20]
It should list all the products that have contratations their code,name and the contratation code ,please

**Comment by Jroge** [comment]
It's in the documentation, https://documenter.getpostman.com/view/7410340/SzKZsvue?version=latest#bbaa6f11-1aba-45f6-8eda-8c281231d79c this one

**Comment by Jroge** [comment]
There is no code in products table

**Comment by Jroge** [comment]
@pablotardio  Close the issue 👁
